# Generated by Django 4.2.30 on 2026-10-03 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=100, verbose_name='客户ID')),
                ('customer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='客户昵称')),
                ('is_transferred', models.BooleanField(default=False, verbose_name='已转人工')),
                ('ai_fail_count', models.IntegerField(default=0, verbose_name='AI连续兜底计数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '会话',
                'verbose_name_plural': '会话',
            },
        ),
        migrations.CreateModel(
            name='ShopAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='店铺名称')),
                ('platform', models.CharField(choices=[('douyin', '抖店/飞鸽')], default='douyin', max_length=20, verbose_name='平台')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('auto_reply', models.BooleanField(default=False, verbose_name='自动回复（关闭=草稿模式）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '店铺账号',
                'verbose_name_plural': '店铺账号',
            },
        ),
        migrations.CreateModel(
            name='TransferRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(max_length=500, verbose_name='关键词（逗号分隔）')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopaccount', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '转人工规则',
                'verbose_name_plural': '转人工规则',
            },
        ),
        migrations.CreateModel(
            name='ReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incoming', models.TextField(verbose_name='客户消息')),
                ('reply', models.TextField(verbose_name='系统回复')),
                ('source', models.CharField(help_text='transfer / keyword / ai / default', max_length=20, verbose_name='决策来源')),
                ('latency_ms', models.IntegerField(default=0, verbose_name='耗时毫秒')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '回复日志',
                'verbose_name_plural': '回复日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReplaceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern', models.CharField(max_length=200, verbose_name='被替换文本')),
                ('replacement', models.CharField(max_length=200, verbose_name='替换为')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopaccount', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '出站替换规则',
                'verbose_name_plural': '出站替换规则',
            },
        ),
        migrations.CreateModel(
            name='KeywordRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(help_text='多个关键词用英文逗号分隔，任一命中即触发', max_length=500, verbose_name='关键词（逗号分隔）')),
                ('reply', models.TextField(verbose_name='回复话术')),
                ('priority', models.IntegerField(default=0, verbose_name='优先级（越大越先）')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopaccount', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '关键词规则',
                'verbose_name_plural': '关键词规则',
                'ordering': ['-priority'],
            },
        ),
        migrations.AddField(
            model_name='chatsession',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopaccount', verbose_name='店铺'),
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('in', '客户 → 客服'), ('out', '客服 → 客户')], max_length=10, verbose_name='方向')),
                ('content', models.TextField(verbose_name='内容')),
                ('source', models.CharField(blank=True, default='', help_text='keyword / ai / default / human / transfer', max_length=20, verbose_name='回复来源')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.chatsession', verbose_name='会话')),
            ],
            options={
                'verbose_name': '消息',
                'verbose_name_plural': '消息',
                'ordering': ['created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='chatsession',
            unique_together={('shop', 'customer_id')},
        ),
    ]
