# Generated by Django 4.2.30 on 2026-10-05 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='external_id',
            field=models.CharField(blank=True, default=None, max_length=200, null=True, verbose_name='平台消息ID'),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('session', 'external_id'), name='uniq_session_external_id'),
        ),
    ]
