# Generated by Django 4.2.30 on 2026-10-05 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_chatmessage_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='replylog',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='replylog',
            name='reviewed_by',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='replylog',
            name='send_error',
            field=models.TextField(blank=True, default='', verbose_name='发送错误'),
        ),
        migrations.AddField(
            model_name='replylog',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='发送时间'),
        ),
        migrations.AddField(
            model_name='replylog',
            name='status',
            field=models.CharField(choices=[('draft', '草稿'), ('sent', '已发送'), ('transferred', '已转人工'), ('rejected', '已驳回'), ('failed', '发送失败')], default='draft', max_length=20, verbose_name='状态'),
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='manual_send_enabled',
            field=models.BooleanField(default=False, help_text='开启后，管理员可在"回复日志"中人工批准发送草稿。默认关闭。', verbose_name='允许人工审核发送'),
        ),
        migrations.AlterField(
            model_name='shopaccount',
            name='platform',
            field=models.CharField(choices=[('douyin', '抖店客服')], default='douyin', max_length=20, verbose_name='平台'),
        ),
        migrations.CreateModel(
            name='PollerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='最后轮询')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='最后成功')),
                ('last_error', models.TextField(blank=True, default='', verbose_name='最后错误')),
                ('consecutive_failures', models.IntegerField(default=0, verbose_name='连续失败次数')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.shopaccount', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '轮询心跳',
                'verbose_name_plural': '轮询心跳',
            },
        ),
    ]
