# Generated by Django 4.2.30 on 2026-10-06 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_replylog_reviewed_at_replylog_reviewed_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KnowledgeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('file', models.FileField(upload_to='kb/%Y/%m/', verbose_name='文件')),
                ('doc_type', models.CharField(blank=True, help_text='txt / md / pdf / docx / xlsx', max_length=10, verbose_name='类型')),
                ('status', models.CharField(choices=[('pending', '待入库'), ('indexing', '入库中'), ('ready', '已就绪'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('chunk_count', models.IntegerField(default=0, verbose_name='分块数')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopaccount', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '知识库文档',
                'verbose_name_plural': '知识库文档',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='KnowledgeChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0, verbose_name='序号')),
                ('content', models.TextField(verbose_name='内容')),
                ('embedding', models.TextField(blank=True, default='', verbose_name='向量JSON')),
                ('doc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='core.knowledgedoc', verbose_name='文档')),
            ],
            options={
                'verbose_name': '知识分块',
                'verbose_name_plural': '知识分块',
                'ordering': ['ordering'],
            },
        ),
    ]
