# Generated by Django 4.2.30 on 2026-10-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_knowledgedoc_knowledgechunk'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='msg/%Y/%m/', verbose_name='图片'),
        ),
        migrations.AddField(
            model_name='replylog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='draft/%Y/%m/', verbose_name='配图'),
        ),
    ]
