# Generated by Django 4.2.30 on 2026-10-08 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_chatmessage_image_replylog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopaccount',
            name='douyin_username',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='抖店登录账号（备注）'),
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='login_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次检测登录'),
        ),
        migrations.AddField(
            model_name='shopaccount',
            name='login_ok',
            field=models.BooleanField(default=False, verbose_name='登录态有效'),
        ),
        migrations.CreateModel(
            name='LoginJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('qr', '扫码登录'), ('password', '账号密码登录'), ('check', '检测登录状态')], max_length=20, verbose_name='方式')),
                ('status', models.CharField(choices=[('running', '进行中'), ('waiting_qr', '等待扫码'), ('success', '成功'), ('failed', '失败')], default='running', max_length=20, verbose_name='状态')),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='login_qr/', verbose_name='二维码')),
                ('error', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shopaccount', verbose_name='店铺')),
            ],
            options={
                'verbose_name': '登录任务',
                'verbose_name_plural': '登录任务',
                'ordering': ['-created_at'],
            },
        ),
    ]
